name: Log Expense

input_schema:
  type: object
  properties:
    amount:
      type: number
    category:
      type: string
    description:
      type: string

tools:
- name: finance_tool
  system:
    resource: agent
    subresource: tool
    operation: create

main:
- tool: finance_tool
  arguments:
    agent_id: "agent.id"
    data:
      amount: inputs[0].amount
      category: inputs[0].category
      description: inputs[0].description