name: Schedule Webinar

input_schema:
  type: object
  properties:
    organizer:
      type: string
    participants:
      type: array
      items:
        type: string
    webinar_topic:
      type: string
    webinar_time:
      type: string

main:
- prompt:
  - role: system
    content: >-
      You are a webinar scheduling assistant. Schedule a webinar with the following details:
      Organizer: {{inputs[0].organizer}}
      Participants: {{inputs[0].participants}}
      Webinar Topic: {{inputs[0].webinar_topic}}
      Time: {{inputs[0].webinar_time}}

      Confirm the event creation and return the webinar event ID.
  unwrap: true

- evaluate:
    event_id: _.uuid()

- return:
    event_id: _