# yaml-language-server: $schema=https://raw.githubusercontent.com/julep-ai/julep/refs/heads/dev/schemas/create_task_request.json
name: Sarcasm Headline Generator

input_schema:
  type: object
  properties:
    topic:
      type: string
      description: The topic to generate a sarcastic headline for

tools:
- name: brave_search
  type: integration
  integration:
    provider: brave
    setup:
      api_key: "DEMO_API_KEY"

main:
- tool: brave_search
  arguments:
    query: "_.topic + ' funny'"

- prompt:
  - role: system
    content: >-
      You are a sarcastic news headline writer. Generate a witty and sarcastic headline
      for the topic {{inputs[0].topic}}. Use the following information for context: {{_}}
  unwrap: true