name: Document Upload, Indexing and Search

input_schema:
  type: object
  properties:
    query:
      type: string
    documents:
      type: array
      items:
        type: object
        properties:
          tile:  
            type: string
          content: 
            type: string
          metadata:
            type: object
                                 
tools:
- name: document_create
  system:
    resource: agent
    subresource: doc
    operation: create   

- name: document_search
  system:
    resource: agent
    subresource: doc
    operation: search                          

main:
- over: inputs[0].documents
  map:
    tool: document_create
    arguments:
      agent_id: "agent.id"
      data:
        title: _.title
        content: _.content
        metadata: _.metadata
                                 
- prompt:
  - role: system
    content: >-
      You have successfully uploaded and indexed {{len(outputs[0])}} documents.
      Provide a summary of the uploaded documents.

- tool: document_search
  arguments:
    agent_id: "agent.id"
    text: inputs[0].query

- prompt:
  - role: system
    content: >-
      Based on the search results, provide a summary of the most relevant documents found.
      Search query: {{inputs[0].query}}
      Number of results: {{len(outputs[0])}}
      
      Results:
      {{outputs[0]}}