# yaml-language-server: $schema=https://raw.githubusercontent.com/julep-ai/julep/refs/heads/dev/schemas/create_task_request.json
name: Tourist Plan With Weather And Attractions
description: Create detailed travel itineraries considering weather conditions and local attractions for multiple locations.

################################################################################
############################# INPUT SCHEMA #####################################
################################################################################
input_schema:
  type: object
  properties:
    locations:
      type: array
      items:
        type: string
      description: The locations to search for.

################################################################################
############################# TOOLS ############################################
################################################################################

# Describing the tools that will be used in the workflow
tools:
- name: wikipedia
  type: integration
  integration:
    provider: wikipedia

- name: weather
  type: integration
  integration:
    provider: weather
    setup:
      openweathermap_api_key: "DEMO_API_KEY"

- name: internet_search
  type: integration
  integration:
    provider: brave
    setup:
      api_key: "DEMO_API_KEY"

################################################################################
############################# MAIN WORKFLOW ####################################
################################################################################
main:
# Step 0: Get weather information for all locations
- over: inputs[0].locations
  map:
    tool: weather
    arguments:
      location: _

# Step 1: Search for tourist attractions in each location
- over: inputs[0].locations
  map:
    tool: internet_search
    arguments:
      query: "'tourist attractions in ' + _"

# Step 2: Combine location data
# Zip locations, weather, and attractions into a list of tuples [(location, weather, attractions)]
- evaluate:
    zipped: |-
      list(
        zip(
          inputs[0].locations,
          [output['result'] for output in outputs[0]],
          outputs[1]
        )
      )

# Step 3: Generate detailed itineraries for each location
- over: _['zipped']
  parallelism: 3
  # Inside the map step, each `_` represents the current element in the list
  # which is a tuple of (location, weather, attractions)
  map:
    prompt:
    - role: system
      content: >-
        You are {{agent.name}}. Your task is to create a detailed itinerary
        for visiting tourist attractions in some locations.
        The user will give you the following information for each location:

        - The location
        - The current weather condition
        - The top tourist attractions
    - role: user
      content: >-
        Location: "{{_[0]}}"
        Weather: "{{_[1]}}"
        Attractions: "{{_[2]}}"
    unwrap: true

# Step 4: Format and combine all itineraries
- evaluate:
    final_plan: |-
      '\\n---------------\\n'.join(activity for activity in _)