# Agents Section
[agents.order_agent]
definition = { path = "./agent.yaml" }

# Tasks Section
[tasks.place_order]
agent_id = { ref = "agents.order_agent.id" }
definition = { path = "./workflow.yaml" }