name: Order Placement

input_schema:
  type: object
  properties:
    user_id:
      type: string
    order_details:
      type: object
      properties:
        item_id:
          type: integer
        quantity:
          type: integer

main:
- prompt:
  - role: system
    content: >-
      You are an order placement assistant. Process the following order:
      User ID: {{inputs[0].user_id}}
      Order Details: {{inputs[0].order_details}}

      Confirm the order placement and return the order ID.
  unwrap: true

- evaluate:
    order_id: _.uuid()

- return:
    order_id: _