# yaml-language-server: $schema=https://raw.githubusercontent.com/julep-ai/julep/refs/heads/dev/schemas/create_task_request.json
name: Julep Comprehensive Analysis Report
description: Create a comprehensive analysis report on the given topic and location.

################################################################################
############################# INPUT SCHEMA #####################################
################################################################################
input_schema:
  type: object
  properties:
    topic:
      type: string
      description: The main topic to analyze.
    location:
      type: string
      description: A location related to the topic for weather and news analysis.

################################################################################
############################# TOOLS ############################################
################################################################################

# Describing the tools that will be used in the workflow
tools:
- name: brave_search
  type: integration
  integration:
    provider: brave
    setup:
      brave_api_key: $ {secrets.BRAVE_API_KEY}

- name: weather
  type: integration
  integration:
    provider: weather
    setup:
      openweathermap_api_key: $ {secrets.OPENWEATHERMAP_API_KEY}

- name: wikipedia
  type: integration
  integration:
    provider: wikipedia

################################################################################
############################# MAIN WORKFLOW ####################################
################################################################################
main:
# Step 0: Get the latest developments on the topic from Brave Search
- tool: brave_search
  arguments:
    query: $ steps[0].input.topic + " latest developments"

# Step 1: Get the weather data for the location
- tool: weather
  arguments:
    location: $ steps[0].input.location

# Step 2: Get the Wikipedia data for the topic
- tool: wikipedia
  arguments:
    query: $ steps[0].input.topic

# Step 3: Create the comprehensive analysis report
- prompt:
  - role: system
    content: >-
      $ f"""
      You are a comprehensive analyst. Your task is to create a detailed report on the topic {steps[0].input.topic} 
      using the information gathered from various sources. Include the following sections in your report:
      
      1. Overview (based on Wikipedia data)
      2. Latest Developments (based on Brave Search results)
      3. Weather Impact (if applicable, based on weather data for {{inputs[0].location}})
      4. Analysis and Conclusions
      
      Use the following data for your report:
      
      Brave Search Results: {steps[0].output}
      Weather Data: {steps[1].output}
      Wikipedia Data: {steps[2].output}
      
      Provide a well-structured, informative report that synthesizes information from all these sources.
      """
  unwrap: true