name: Comprehensive Analysis Report

input_schema:
  type: object
  properties:
    topic:
      type: string
      description: The main topic to analyze.
    location:
      type: string
      description: A location related to the topic for weather and news analysis.

tools:
- name: brave_search
  type: integration
  integration:
    provider: brave
    setup:
      api_key: "YOUR_API_KEY"

- name: weather
  type: integration
  integration:
    provider: weather
    setup:
      openweathermap_api_key: "YOUR_API_KEY"

- name: wikipedia
  type: integration
  integration:
    provider: wikipedia

main:
- tool: brave_search
  arguments:
    query: "inputs[0].topic + ' latest developments'"

- tool: weather
  arguments:
    location: inputs[0].location

- tool: wikipedia
  arguments:
    query: inputs[0].topic

- prompt:
  - role: system
    content: >-
      You are a comprehensive analyst. Your task is to create a detailed report on the topic {{inputs[0].topic}} 
      using the information gathered from various sources. Include the following sections in your report:
      
      1. Overview (based on Wikipedia data)
      2. Latest Developments (based on Brave Search results)
      3. Weather Impact (if applicable, based on weather data for {{inputs[0].location}})
      4. Analysis and Conclusions
      
      Use the following data for your report:
      
      Brave Search Results: {{outputs[0]}}
      Weather Data: {{outputs[1]}}
      Wikipedia Data: {{outputs[2]}}
      
      Provide a well-structured, informative report that synthesizes information from all these sources.
  unwrap: true