name: Payment Processing

input_schema:
  type: object
  properties:
    user_id:
      type: string
    order_id:
      type: string
    amount:
      type: number

main:
- prompt:
  - role: system
    content: >-
      You are a payment processor. Process payment for the following order:
      User ID: {{inputs[0].user_id}}
      Order ID: {{inputs[0].order_id}}
      Amount: {{inputs[0].amount}}

      Confirm payment status (success or failure).
  unwrap: true

- evaluate:
    payment_status: "success"  # Simulating a successful payment

- return:
    payment_status: _