# yaml-language-server: $schema=https://raw.githubusercontent.com/julep-ai/julep/refs/heads/dev/schemas/create_task_request.json
name: Hello World

main:
- prompt:
    - role: system
      content: "You are a helpful assistant"
    - role: user
      content: "Tell me a joke!"

