# Agents Section
[agents.news_agent]
definition = { path = "./agent.yaml" }

# Tasks Section
[tasks.recommend_news]
agent_id = { ref = "agents.news_agent.id" }
definition = { path = "./workflow.yaml" }