name: generate_update_persona

# Define the input schema for the workflow
input_schema:
  type: object
  properties:
    user_ppid:
      type: string
    articles_read:
      type: array
      items:
        type: string
  required:
    - user_ppid
    - articles_read

# Define the tools that are going to be used in the workflow
tools:
  - name: get_user_from_ppid
    description: Get a user from the user ppid
    type: system
    system:
      resource: user
      operation: list
    
  - name: list_user_docs
    description: List the user docs
    type: system
    system:
      resource: user
      subresource: doc
      operation: list

  - name: create_user_doc
    description: Create a user doc
    type: system
    system:
      resource: user
      subresource: doc
      operation: create

main:
  # Get the user from the ppid using metadata_filter (returns a list)
  - tool: get_user_from_ppid
    arguments:
      limit: "1"
      sort_by: "'created_at'"
      direction: "'desc'"
      metadata_filter:
        ppid: inputs[0]['user_ppid']

  # Unwrap the list to get the user
  - evaluate:
      user: _[0]


  # Get the user persona document using metadata_filter (returns a list)
  - tool: list_user_docs
    arguments:
      user_id: _['user']['id']
      limit: "1"
      sort_by: "'created_at'"
      direction: "'desc'"

  # Get the doc if it exists
  - evaluate:
      doc: _[0] if len(_) > 0 else {}


  # Get the user persona from the doc if the doc exists
  - evaluate:
      user_persona: _['doc'].get('content', "")


  # Create the user persona using the prompt step
  - prompt:
      - role: user
        content: |
          You are an expert at creating detailed user personas for sports fans. Your task is to write a comprehensive user persona based on the provided user data and article reads. This persona will help in recommending articles to the user.

          #Input#
          Following is the user data 
          User details:
          {{outputs[1].user.metadata}}
                          
          User reading history:
          {{inputs[0].articles_read}}
          
          User past persona:
          {{_.user_persona}}

          #Task#
          Let's think of the following steps carefully. Using the user data, create a user persona that includes the following sections:

          1. Demographics
          2. Psychographics
          3. Content Interests


          For each section, follow these process:

          1. Demographics:
            - Provide the user's age, gender, and location.
            - If any information is missing, make a reasonable assumption based on other details provided.

          2. Psychographics:
            - Describe the user's personality traits.
            - Create an interest graph that shows the user's primary and secondary interests related to sports, sports figures and other relevant areas.

          3. Content Interests:
            - List and briefly describe the user's thematic interests.
            - Specify article categories that would appeal to this user.
            - Identify entity preferences (e.g., specific teams, athletes, or sports figures).
            - Detail the user's sports preferences, including favorite sports, leagues, and events.
            - Assess the user's engagement level with sports content (e.g., casual, dedicated, or super-fan).
            - Draw any correlations between the user's interests in various topics, sports, and entities.
            - Detail the user's content needs and expectations  


          #Instructions#

          When writing the user persona:
          - Be specific and provide examples where possible.
          - Make logical inferences based on the given information.
          - Ensure consistency throughout the persona.
          - Use bullet points or short paragraphs for easy readability.

          Format your response as follows:
          - Use headers for each main section (Demographics, Psychographics, Content Interests).
          - Use subheaders for subsections within Content Interests.
          - Include a brief introduction and conclusion.

          Present your final user persona within <user_persona> tags. Begin with a concise introduction, then proceed with the detailed sections as outlined above.
          Your work will be evaluated for comprehensive and detailed persona.
    unwrap: true
    tool_choice: none  

  # Create a new persona document
  - tool: create_user_doc
    arguments:
      user_id: inputs[2]['user']['id']
      data:
        embed_instruction: "'Represent the query for User persona used for document retrieval: '"
        title: "'User Persona'"
        content: _